name: Build and test
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install fmt llvm make pkg-config
      - name: Build executable
        run: |
          cd znoc
          LLVM_CONFIG=`brew --prefix llvm`/bin/llvm-config CC=clang CXX=clang++ gmake
      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: znoc-macos
          path: znoc/build/znoc
      - name: Upload built objects
        uses: actions/upload-artifact@v2
        with:
          name: znoc-macos-obj
          path: znoc/build/**/*.o
          retention-days: 1

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libfmt-dev llvm
      - name: Build executable
        run: |
          cd znoc
          CC=clang CXX=clang++ make
      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: znoc-linux
          path: znoc/build/znoc
      - name: Upload built objects
        uses: actions/upload-artifact@v2
        with:
          name: znoc-linux-obj
          path: znoc/build/**/*.o
          retention-days: 1
  
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-llvm mingw-w64-x86_64-clang mingw-w64-x86_64-fmt
      - name: Build executable
        run: |
          cd znoc
          CC=clang CXX=clang++ mingw32-make
      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: znoc-windows
          path: znoc/build/znoc.exe
      - name: Upload built objects
        uses: actions/upload-artifact@v2
        with:
          name: znoc-windows-obj
          path: znoc/build/**/*.o
          retention-days: 1


  test-macos:
    runs-on: macos-latest
    needs: build-macos
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Download built object code
        uses: actions/download-artifact@v2
        with:
          name: znoc-macos-obj
          path: znoc/build/
          if-no-files-found: error
      - name: Install dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install fmt llvm make pkg-config
      - name: Run tests
        run: |
          cd znoc
          LLVM_CONFIG=`brew --prefix llvm`/bin/llvm-config CC=clang CXX=clang++ gmake test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: znoc-macos-test-results
          path: znoc/test/unit/build/out.xml
          retention-days: 1
  
  test-linux:
    runs-on: ubuntu-latest
    needs: linux-macos
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Download built object code
        uses: actions/download-artifact@v2
        with:
          name: znoc-linux-obj
          path: znoc/build/
          if-no-files-found: error
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libfmt-dev llvm
      - name: Run tests
        run: |
          cd znoc
          CC=clang CXX=clang++ make test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: znoc-linux-test-results
          path: znoc/test/unit/build/out.xml
          retention-days: 1

  publish-tests:
    runs-on: ubuntu-latest
    needs: [test-macos, test-linux]
    if: always()
    steps:
      - name: Download test results (macos)
        uses: actions/download-artifact@v2
        with:
          name: znoc-macos-test-results
          if-no-files-found: error
          path: macos.xml
      - name: Download test results (linux)
        uses: actions/download-artifact@v2
        with:
          name: znoc-linux-test-results
          if-no-files-found: error
          path: linux.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: *.xml