name: Build and test
on: [push, pull_request]

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install fmt llvm
      - name: Build executable
        run: |
          export PATH="/usr/local/opt/llvm/bin:$PATH"
          llvm-config --cppflags
          cd znoc
          CC=clang CXX=clang++ make
      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: znoc
          path: znoc/build/znoc