name: Build and test
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  Build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install fmt llvm make pkg-config
      - name: Build executable
        run: |
          cd znoc
          LLVM_CONFIG=`brew --prefix llvm`/bin/llvm-config CC=clang CXX=clang++ gmake
      - name: Build tests
        run: |
          cd znoc
          LLVM_CONFIG=`brew --prefix llvm`/bin/llvm-config CC=clang CXX=clang++ gmake test
      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: znoc-macos
          path: znoc/build/znoc
      - name: Upload built tests
        uses: actions/upload-artifact@v2
        with:
          name: znoc-macos-tests
          path: znoc/test/unit/build/znoc-test-numeric_literal
          retention-days: 1

  Build_Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libfmt-dev llvm
      - name: Build executable
        run: |
          cd znoc
          CC=clang CXX=clang++ make
      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: znoc-linux
          path: znoc/build/znoc
      - name: Upload built objects
        uses: actions/upload-artifact@v2
        with:
          name: znoc-linux-obj
          path: znoc/build/**/*.o
          retention-days: 1
  
  Build_Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-llvm mingw-w64-x86_64-clang mingw-w64-x86_64-fmt
      - name: Build executable
        run: |
          cd znoc
          CC=clang CXX=clang++ mingw32-make
      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: znoc-windows
          path: znoc/build/znoc.exe
      - name: Upload built objects
        uses: actions/upload-artifact@v2
        with:
          name: znoc-windows-obj
          path: znoc/build/**/*.o
          retention-days: 1


  Test_macos:
    runs-on: macos-latest
    needs: Build_macos
    steps:
      - name: Download tests
        uses: actions/download-artifact@v2
        with:
          name: znoc-macos-tests
          if-no-files-found: error
      - name: Install dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install fmt llvm
      - name: Run test executable
        run: |
          ./znoc-test-numeric_literal --gtest_output="xml:out.xml"
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: znoc-macos-test-results
          path: out.xml
          retention-days: 1

  Publish_tests:
    runs-on: ubuntu-latest
    needs: [Test_macos]
    if: always()
    steps:
      - name: Download built object code
        uses: actions/download-artifact@v2
        with:
          name: znoc-macos-test-results
          if-no-files-found: error
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: out.xml