name: Build and test
on: [push, pull_request]

jobs:
  Build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install fmt llvm
      - name: Build executable
        run: |
          export PATH="/usr/local/opt/llvm/bin:$PATH"
          export C_INCLUDE_PATH="/usr/local/include:$C_INCLUDE_PATH"
          export CPLUS_INCLUDE_PATH="/usr/local/include:$CPLUS_INCLUDE_PATH"
          export LIBRARY_PATH="/usr/local/lib:$LIBRARY_PATH"
          cd znoc
          CC=clang CXX=clang++ make
      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: znoc-macos
          path: znoc/build/znoc

  Build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install libfmt-dev llvm
      - name: Build executable
        run: |
          cd znoc
          CC=clang CXX=clang++ make
      - name: Upload built executable
        uses: actions/upload-artifact@v2
        with:
          name: znoc-linux
          path: znoc/build/znoc